mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.clustertech

mysql:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true&serverTimezone=UTC

server:
  port: 12001

